BIN_BLUE = "BLUE"
BIN_GREEN = "GREEN"
BIN_RED = "RED"
BIN_GREY = "GREY"

STREAM_DRY = "DRY"
STREAM_WET = "WET"
STREAM_HAZARDOUS = "HAZARDOUS"

WASTE_TYPES = {
    "pet_bottle": {
        "plural": "PET Bottles",
        "label": "PET Bottle",
        "key": "petBottles",
        "bin": BIN_BLUE,
        "recyclable": True,
        "price": 25,
        "reward": 5,
        "carbon": 0.15,
        "weight": 0.03,
        "category": "PLASTIC",
        "stream": STREAM_DRY,
    },
    "hdpe_bottle": {
        "plural": "HDPE Bottles",
        "label": "HDPE Bottle",
        "key": "hdpeBottles",
        "bin": BIN_BLUE,
        "recyclable": True,
        "price": 30,
        "reward": 5,
        "carbon": 0.18,
        "weight": 0.05,
        "category": "PLASTIC",
        "stream": STREAM_DRY,
    },
    "glass_bottle": {
        "plural": "Glass Bottles",
        "label": "Glass Bottle",
        "key": "glassBottles",
        "bin": BIN_GREEN,
        "recyclable": True,
        "price": 2,
        "reward": 6,
        "carbon": 0.25,
        "weight": 0.4,
        "category": "GLASS",
        "stream": STREAM_DRY,
    },
    "aluminium_can": {
        "plural": "Aluminium Cans",
        "label": "Aluminium Can",
        "key": "aluminiumCans",
        "bin": BIN_BLUE,
        "recyclable": True,
        "price": 120,
        "reward": 10,
        "carbon": 0.4,
        "weight": 0.015,
        "category": "METAL",
        "stream": STREAM_DRY,
    },
    "plastic_wrapper": {
        "plural": "Plastic Wrappers",
        "label": "Plastic Wrapper",
        "key": "plasticWrappers",
        "bin": BIN_GREY,
        "recyclable": False,
        "price": 0,
        "reward": 1,
        "carbon": 0.02,
        "weight": 0.003,
        "category": "PLASTIC",
        "stream": STREAM_DRY,
    },
    "food_container": {
        "plural": "Food Containers",
        "label": "Food Container",
        "key": "foodContainers",
        "bin": BIN_BLUE,
        "recyclable": True,
        "price": 15,
        "reward": 4,
        "carbon": 0.1,
        "weight": 0.02,
        "category": "PLASTIC",
        "stream": STREAM_DRY,
    },
    "plastic_cup": {
        "plural": "Plastic Cups",
        "label": "Plastic Cup",
        "key": "plasticCups",
        "bin": BIN_BLUE,
        "recyclable": True,
        "price": 10,
        "reward": 3,
        "carbon": 0.08,
        "weight": 0.01,
        "category": "PLASTIC",
        "stream": STREAM_DRY,
    },
    "light_bulb": {
        "plural": "Light Bulbs",
        "label": "Light Bulb",
        "key": "lightBulbs",
        "bin": BIN_RED,
        "recyclable": False,
        "price": 0,
        "reward": 8,
        "carbon": 0.05,
        "weight": 0.05,
        "category": "HAZARDOUS",
        "stream": STREAM_HAZARDOUS,
    },
    "battery": {
        "plural": "Batteries",
        "label": "Battery",
        "key": "batteries",
        "bin": BIN_RED,
        "recyclable": True,
        "price": 30,
        "reward": 15,
        "carbon": 0.5,
        "weight": 0.05,
        "category": "HAZARDOUS",
        "stream": STREAM_HAZARDOUS,
    },
    "e_waste": {
        "plural": "E-Waste",
        "label": "E-Waste",
        "key": "eWaste",
        "bin": BIN_RED,
        "recyclable": True,
        "price": 60,
        "reward": 20,
        "carbon": 1.2,
        "weight": 1.5,
        "category": "E_WASTE",
        "stream": STREAM_HAZARDOUS,
    },
    "paper": {
        "plural": "Paper",
        "label": "Paper",
        "key": "paper",
        "bin": BIN_BLUE,
        "recyclable": True,
        "price": 12,
        "reward": 4,
        "carbon": 0.1,
        "weight": 0.2,
        "category": "PAPER",
        "stream": STREAM_DRY,
    },
    "cardboard": {
        "plural": "Cardboard",
        "label": "Cardboard",
        "key": "cardboard",
        "bin": BIN_BLUE,
        "recyclable": True,
        "price": 8,
        "reward": 4,
        "carbon": 0.12,
        "weight": 0.3,
        "category": "PAPER",
        "stream": STREAM_DRY,
    },
    "scrap_metal": {
        "plural": "Scrap Metal",
        "label": "Scrap Metal",
        "key": "scrapMetal",
        "bin": BIN_BLUE,
        "recyclable": True,
        "price": 30,
        "reward": 12,
        "carbon": 0.6,
        "weight": 0.2,
        "category": "METAL",
        "stream": STREAM_DRY,
    },
    "textile": {
        "plural": "Textiles",
        "label": "Textile",
        "key": "textile",
        "bin": BIN_GREY,
        "recyclable": False,
        "price": 5,
        "reward": 3,
        "carbon": 0.2,
        "weight": 0.3,
        "category": "TEXTILE",
        "stream": STREAM_DRY,
    },
    "organic": {
        "plural": "Organic Waste",
        "label": "Organic Waste",
        "key": "organicWaste",
        "bin": BIN_GREEN,
        "recyclable": False,
        "price": 0,
        "reward": 2,
        "carbon": 0.0,
        "weight": 0.15,
        "category": "ORGANIC",
        "stream": STREAM_WET,
    },
    "general": {
        "plural": "Mixed Waste",
        "label": "Mixed Waste",
        "key": "mixedWaste",
        "bin": BIN_GREY,
        "recyclable": False,
        "price": 0,
        "reward": 1,
        "carbon": 0.0,
        "weight": 0.1,
        "category": "NON_RECYCLABLE",
        "stream": STREAM_DRY,
    },
}

LABEL_MAP = {
    "bottle": "pet_bottle",
    "pet bottle": "pet_bottle",
    "plastic bottle": "pet_bottle",
    "water bottle": "pet_bottle",
    "hdpe bottle": "hdpe_bottle",
    "detergent bottle": "hdpe_bottle",
    "milk jug": "hdpe_bottle",
    "wine glass": "glass_bottle",
    "glass bottle": "glass_bottle",
    "glass": "glass_bottle",
    "vase": "glass_bottle",
    "jar": "glass_bottle",
    "can": "aluminium_can",
    "tin can": "aluminium_can",
    "aluminium can": "aluminium_can",
    "aluminum can": "aluminium_can",
    "soda can": "aluminium_can",
    "beverage can": "aluminium_can",
    "wrapper": "plastic_wrapper",
    "plastic wrapper": "plastic_wrapper",
    "packet": "plastic_wrapper",
    "sachet": "plastic_wrapper",
    "plastic bag": "plastic_wrapper",
    "food container": "food_container",
    "container": "food_container",
    "tupperware": "food_container",
    "cup": "plastic_cup",
    "plastic cup": "plastic_cup",
    "bowl": "food_container",
    "light bulb": "light_bulb",
    "lightbulb": "light_bulb",
    "bulb": "light_bulb",
    "tube light": "light_bulb",
    "battery": "battery",
    "cell phone": "e_waste",
    "laptop": "e_waste",
    "keyboard": "e_waste",
    "mouse": "e_waste",
    "remote": "e_waste",
    "tv": "e_waste",
    "monitor": "e_waste",
    "microwave": "e_waste",
    "toaster": "e_waste",
    "hair drier": "e_waste",
    "clock": "e_waste",
    "book": "paper",
    "paper": "paper",
    "newspaper": "paper",
    "cardboard": "cardboard",
    "box": "cardboard",
    "carton": "cardboard",
    "fork": "scrap_metal",
    "knife": "scrap_metal",
    "spoon": "scrap_metal",
    "scissors": "scrap_metal",
    "metal": "scrap_metal",
    "tie": "textile",
    "handbag": "textile",
    "backpack": "textile",
    "umbrella": "textile",
    "shoe": "textile",
    "clothes": "textile",
    "banana": "organic",
    "banana peel": "organic",
    "apple": "organic",
    "orange": "organic",
    "broccoli": "organic",
    "carrot": "organic",
    "sandwich": "organic",
    "pizza": "organic",
    "hot dog": "organic",
    "donut": "organic",
    "cake": "organic",
    "food": "organic",
    "trash": "general",
}

MIN_CONFIDENCE_BY_LABEL = {
    "donut": 0.55,
    "cake": 0.55,
    "sandwich": 0.55,
    "hot dog": 0.55,
    "pizza": 0.55,
    "carrot": 0.50,
    "broccoli": 0.50,
    "apple": 0.45,
    "orange": 0.45,
    "banana": 0.45,
    "bowl": 0.50,
    "vase": 0.50,
    "book": 0.45,
    "remote": 0.50,
    "clock": 0.50,
}

_DEFAULT = WASTE_TYPES["general"]


def min_confidence(raw_label):
    return MIN_CONFIDENCE_BY_LABEL.get(raw_label.strip().lower(), 0.0)


def _entry(raw_label):
    normalized = raw_label.strip().lower()
    key = LABEL_MAP.get(normalized) or LABEL_MAP.get(normalized.replace("_", " "))
    if key is None:
        return None
    return WASTE_TYPES.get(key)


def is_waste(raw_label):
    return _entry(raw_label) is not None


def display_label(raw_label):
    entry = _entry(raw_label)
    return entry["label"] if entry else raw_label.title()


def entry_for(raw_label):
    return _entry(raw_label) or _DEFAULT


def catalog():
    return {
        key: {
            "label": value["label"],
            "bin": value["bin"],
            "recyclable": value["recyclable"],
            "estimatedPrice": {"value": value["price"], "unit": "INR/kg"},
            "rewardPoints": value["reward"],
            "carbonSavedKg": value["carbon"],
            "unitWeightKg": value["weight"],
            "category": value["category"],
            "stream": value["stream"],
        }
        for key, value in WASTE_TYPES.items()
    }
